name: Java CI with Maven build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Step 1 - Checkout code
    - uses: actions/checkout@v2
    
    - name: Step 2 - Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
      
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml
