# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Step 1 - checkout
    - uses: actions/checkout@v2
    
    - name: step 2 - Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
        
    - name: Step 3 - Get current directory
      run: echo %CD%
      
    - name: Step 4 - Run mvn test
      run: mvn test    
