name: Java CI with Maven Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout code
    - uses: actions/checkout@v2
    
    - name: Step 2 - Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
        
    - name: Step 3 - Test with Maven
      run: mvn test
